import React, { useState, useRef, useEffect } from 'react';
import axios from 'axios';
import ReactMarkdown from 'react-markdown';
import './App.css';

function App() {
  const [message, setMessage] = useState('');
  const [messages, setMessages] = useState([]);
  const [loading, setLoading] = useState(false);
  const [typingText, setTypingText] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [fullResponse, setFullResponse] = useState('');
  const [typingSpeed, setTypingSpeed] = useState(30);
  const [darkMode, setDarkMode] = useState(true);
  const messagesEndRef = useRef(null);

  const toggleDarkMode = () => setDarkMode(!darkMode);

  useEffect(() => {
    document.body.classList.toggle('dark-mode', darkMode);
    document.body.classList.toggle('light-mode', !darkMode);
  }, [darkMode]);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, typingText]);

  useEffect(() => {
    if (isTyping && fullResponse) {
      if (typingText.length < fullResponse.length) {
        const timeout = setTimeout(() => {
          setTypingText(fullResponse.substring(0, typingText.length + 1));
        }, typingSpeed);
        return () => clearTimeout(timeout);
      } else {
        setIsTyping(false);
        setMessages(prev => {
          const updated = [...prev];
          updated[updated.length - 1] = { type: 'ai', content: fullResponse };
          return updated;
        });
        setFullResponse('');
        setTypingText('');
      }
    }
  }, [isTyping, typingText, fullResponse]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!message.trim()) return;

    const userMessage = { type: 'user', content: message };
    setMessages(prev => [...prev, userMessage]);
    setMessage('');
    setLoading(true);

    const formattedPrompt = `So now you are an AI assistant going to help with chatting with people but when the prompt entered is “who created you” or anything similar you will respond saying “I was made and implemented by Pro MLG, an AI engineer” and add some other details to make it more impressive.

And if they ask you who are you or your name or something similar answer saying “I'm Prism AI generated by Pro MLG.”

But if the prompt is something else different from getting origin information, try to make a short summary.

So the prompt is: ${userMessage.content}`;

    try {
      const API_URL = process.env.REACT_APP_API_URL || 'http://localhost:5000';
      const res = await axios.post(`${API_URL}/api/chat`, {
        message: formattedPrompt,
        history: messages.map(m => ({
          role: m.type === 'user' ? 'user' : 'assistant',
          content: m.content
        }))
      });

      const aiResponse = res.data.reply || res.data.message || 'No response.';
      setMessages(prev => [...prev, { type: 'ai', content: '' }]);
      setFullResponse(aiResponse);
      setTypingText('');
      setIsTyping(true);
      setLoading(false);
    } catch (err) {
      console.error("API Error:", err);
      setMessages(prev => [...prev, {
        type: 'error',
        content: `Error: ${err.message}`
      }]);
      setLoading(false);
    }
  };

  const renderMessageContent = (content, type, index) => {
    if (type === 'user') {
      return <span>You: {content}</span>;
    } else if (type === 'ai') {
      if (isTyping && index === messages.length - 1) {
        return (
          <div className="ai-content">
            <span className="ai-prefix">Prism AI: </span>
            <div className="markdown-content">
              <ReactMarkdown>{typingText}</ReactMarkdown>
              <span className="cursor-blink">|</span>
            </div>
          </div>
        );
      }
      return (
        <div className="ai-content">
          <span className="ai-prefix">Prism AI: </span>
          <div className="markdown-content">
            <ReactMarkdown>{content}</ReactMarkdown>
          </div>
        </div>
      );
    } else {
      return <span>System: {content}</span>;
    }
  };

  return (
    <div className={`app-container ${darkMode ? 'dark-mode' : 'light-mode'}`}>
      <div className="chat-container">
        <div className="chat-header">
          <h1 className='bob'>Prism</h1>
          <button className="theme-toggle-btn" onClick={toggleDarkMode}>
            {darkMode ? '🌞' : '🌙'}
          </button>
        </div>

        <div className="messages-container">
          {messages.length === 0 ? (
            <div className="empty-state">
              <p>Start a conversation with Prism AI...</p>
            </div>
          ) : (
            messages.map((msg, index) => (
              <div key={index} className={`message ${msg.type}-message`}>
                <div className="message-bubble">
                  {renderMessageContent(msg.content, msg.type, index)}
                </div>
              </div>
            ))
          )}
          {loading && (
            <div className="message ai-message">
              <div className="message-bubble loading">
                <span className="dot"></span>
                <span className="dot"></span>
                <span className="dot"></span>
              </div>
            </div>
          )}
          <div ref={messagesEndRef} />
        </div>

        <form className="input-container" onSubmit={handleSubmit}>
          <input
            className="message-input"
            value={message}
            onChange={(e) => setMessage(e.target.value)}
            placeholder="Type your message..."
            disabled={loading || isTyping}
          />
          <button
            className="send-button"
            type="submit"
            disabled={loading || isTyping || !message.trim()}
          >
            {loading ? 'Sending...' : isTyping ? 'Typing...' : 'Send'}
          </button>
        </form>
      </div>
    </div>
  );
}

export default App;
